sudo: false
language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - platform-tools  

jdk:
  - oraclejdk8

script: ./gradlew build --stacktrace -i

cache:
  directories:
    - "$HOME/.gradle/caches"

branches:
  only:
    - master
